Dans ce notebook on va séparer en train et test nos données avant analyse préalable de la base pour éviter toute forme de data leakage.

In [1]:
import os 
import pandas as pd 
from sklearn.model_selection import train_test_split
import numpy as np
import plotly.graph_objects as go

In [2]:
print(os.getcwd())
os.chdir("../")
os.getcwd()

c:\Users\leoco\Documents\cours\M2_MOSEF\ML_theory\land_value_prediction\notebooks

'c:\\Users\\leoco\\Documents\\cours\\M2_MOSEF\\ML_theory\\land_value_prediction'

In [3]:
from src.land_value_prediction.train_test_split.analysis_functions import comparer_train_test, identifier_differences_significatives

In [4]:
idf_vf_full = pd.read_parquet("data/processed/idf_vf_full.parquet")
idf_vf_full.head()

,date_mutation,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,...,commune_part_admin_sante,commune_etablissements_par_menage,commune_taux_etablissements_10_plus,commune_sante_score_2013_commune,commune_education_score_2013_commune,commune_revenu_score_2013_commune,commune_idh2_2013_commune,commune_taux_criminalite_moyen,commune_taux_croissance_pop,commune_densite_pop
0,2021-01-01,Vente,169500.0,28.0,ALL HOCHE,4440,92130.0,92040,Issy-les-Moulineaux,92,...,0.090161,0.075901,0.254014,0.700824,0.835437,0.704796,0.747019,0.376209,1.045371,16106.117647
1,2021-01-02,Vente,415000.0,109.0,RUE DES COURLIS,1570,95100.0,95018,Argenteuil,95,...,0.085686,0.071492,0.182996,0.567644,0.364296,0.331115,0.421018,0.561570,0.784827,6400.116144
2,2021-01-02,Vente,415000.0,109.0,RUE DES COURLIS,1570,95100.0,95018,Argenteuil,95,...,0.085686,0.071492,0.182996,0.567644,0.364296,0.331115,0.421018,0.561570,0.784827,6400.116144
3,2021-01-02,Vente,512000.0,97.0,RUE DE CHARONNE,1888,75011.0,75111,Paris 11e Arrondissement,75,...,0.067020,0.131609,0.145909,0.680558,0.851424,0.607516,0.713166,0.996164,-1.129705,39957.220708
4,2021-01-02,Vente,512000.0,97.0,RUE DE CHARONNE,1888,75011.0,75111,Paris 11e Arrondissement,75,...,0.067020,0.131609,0.145909,0.680558,0.851424,0.607516,0.713166,0.996164,-1.129705,39957.220708

On va créer 3 échantillons :  
- échantillons train et test sur 2021-2024  
- échantillon temporel out_of_sample (2025-S1)

Séparation train-test et échantillon out of sample :

In [5]:
train_test = idf_vf_full[idf_vf_full['annee'] < 2025].copy()
out_of_sample_df = idf_vf_full[idf_vf_full['annee'] >= 2025].copy()

print(f"Taille du train-test: {len(train_test)} ({len(train_test)/len(idf_vf_full)*100:.1f}%)")
print(f"Taille du out of sample: {len(out_of_sample_df)} ({len(out_of_sample_df)/len(idf_vf_full)*100:.1f}%)")
print(f"\nPériode train-test: {train_test['date_mutation'].min()} à {train_test['date_mutation'].max()}")
print(f"Période out of sample: {out_of_sample_df['date_mutation'].min()} à {out_of_sample_df['date_mutation'].max()}")

print("\nStatistiques prix_m2 - Train-test:")
train_test['prix_m2'].describe().round(2)

Taille du train-test: 622561 (92.5%)
Taille du out of sample: 50188 (7.5%)

Période train-test: 2021-01-01 00:00:00 à 2024-12-31 00:00:00
Période out of sample: 2025-01-02 00:00:00 à 2025-06-30 00:00:00

Statistiques prix_m2 - Train-test:

count    622561.00
mean       6016.69
std        3660.23
min         500.24
25%        3261.63
50%        4772.73
75%        8238.64
max       19998.89
Name: prix_m2, dtype: float64

In [6]:
print("\nStatistiques prix_m2 - Out of sample:")
out_of_sample_df['prix_m2'].describe().round(2)

Statistiques prix_m2 - Out of sample:

count    50188.00
mean      5825.00
std       3543.62
min        504.00
25%       3181.82
50%       4670.33
75%       7914.29
max      19988.70
Name: prix_m2, dtype: float64

Séparer train et test :

In [7]:
# Créer des déciles sur la variable cible pour stratifier le split
idf_vf_full['prix_m2_bins'] = pd.qcut(idf_vf_full['prix_m2'], q=10, labels=False, duplicates='drop')

# Split train/test avec stratification
train, test = train_test_split(
    idf_vf_full, 
    test_size=0.2, 
    shuffle=True,
    random_state=42, 
    stratify=idf_vf_full['prix_m2_bins']
)

# Supprimer la colonne temporaire de bins
train = train.drop('prix_m2_bins', axis=1)
test = test.drop('prix_m2_bins', axis=1)

print(f"Taille du train set: {len(train)} ({len(train)/len(idf_vf_full)*100:.1f}%)")
print(f"Taille du test set: {len(test)} ({len(test)/len(idf_vf_full)*100:.1f}%)")

print("\nStatistiques prix_m2 - Train:")
train['prix_m2'].describe()

Taille du train set: 538199 (80.0%)
Taille du test set: 134550 (20.0%)

Statistiques prix_m2 - Train:

count    538199.000000
mean       6003.199668
std        3653.826395
min         500.240000
25%        3255.785765
50%        4764.705882
75%        8214.285714
max       19998.888889
Name: prix_m2, dtype: float64

In [8]:
print("\nStatistiques prix_m2 - Test:")
test['prix_m2'].describe()

Statistiques prix_m2 - Test:

count    134550.000000
mean       5999.136593
std        3644.720456
min         501.672241
25%        3255.813953
50%        4764.705882
75%        8209.215550
max       19994.074074
Name: prix_m2, dtype: float64

In [9]:
comparison = comparer_train_test(train, test)
comparison

,type,train_mean,test_mean,diff_mean,train_median,test_median,diff_median,train_std,test_std,diff_std,train_min,test_min,train_max,test_max,diff_mean_pct,diff_median_pct,diff_std_pct
variable,,,,,,,,,,,,,,,,,
date_mutation,categorical,<NA>,<NA>,<NA>,2025-03-31 00:00:00,2025-03-31 00:00:00,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
nature_mutation,categorical,<NA>,<NA>,<NA>,Vente,Vente,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
valeur_fonciere,numeric,393987.832195,395612.682819,-1624.850624,300000.0,300000.0,0.0,352455.681605,353618.438065,-1162.75646,5200.0,6300.0,10500000.0,9639800.0,-0.410718,0.0,-0.328817
adresse_numero,numeric,131.320988,130.284207,1.036781,19.0,19.0,0.0,864.910964,862.16271,2.748254,1.0,1.0,9999.0,9248.0,0.795784,0.0,0.318763
adresse_nom_voie,categorical,<NA>,<NA>,<NA>,RUE DE PARIS,RUE DE PARIS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
adresse_code_voie,categorical,<NA>,<NA>,<NA>,0040,0040,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
code_postal,numeric,85524.218438,85517.361477,6.856961,91220.0,91220.0,0.0,8396.943389,8398.569749,-1.62636,75001.0,75001.0,95880.0,95880.0,0.008018,0.0,-0.019365
code_commune,categorical,<NA>,<NA>,<NA>,75115,75115,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
nom_commune,categorical,<NA>,<NA>,<NA>,Paris 15e Arrondissement,Paris 15e Arrondissement,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
code_departement,categorical,<NA>,<NA>,<NA>,75,75,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
nombre_lots,numeric,1.08681,1.080892,0.005918,1.0,1.0,0.0,0.968757,0.969212,-0.000455,0,0,23,16,0.547514,0.0,-0.046989
code_type_local,numeric,1.675345,1.671795,0.00355,2.0,2.0,0.0,0.468246,0.469562,-0.001315,1.0,1.0,2.0,2.0,0.212354,0.0,-0.28014
type_local,categorical,<NA>,<NA>,<NA>,Appartement,Appartement,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
surface_reelle_bati,numeric,71.888892,72.212687,-0.323794,65.0,65.0,0.0,42.955576,43.172871,-0.217295,10.0,10.0,880.0,880.0,-0.44839,0.0,-0.503314
nombre_pieces_principales,numeric,3.227643,3.23534,-0.007697,3.0,3.0,0.0,1.550885,1.546609,0.004276,1.0,1.0,15.0,15.0,-0.237918,0.0,0.276473
surface_terrain,numeric,576.100737,588.981513,-12.880776,401.0,401.0,0.0,1805.761881,2335.455635,-529.693754,1.0,1.0,448021.0,300000.0,-2.186958,0.0,-22.680532
longitude,numeric,2.360422,2.36101,-0.000588,2.343398,2.343124,0.000274,0.249955,0.250333,-0.000378,1.453111,1.462064,3.518413,3.474918,-0.024912,0.011694,-0.151182
latitude,numeric,48.828705,48.828855,-0.00015,48.853975,48.85398,-0.000005,0.14441,0.144674,-0.000264,48.125164,48.125164,49.234761,49.236552,-0.000307,-0.000009,-0.1824
annee,numeric,2022.518344,2022.516581,0.001762,2022.0,2022.0,0.0,1.269153,1.267658,0.001495,2021,2021,2025,2025,0.000087,0.0,0.11795
semestre,categorical,<NA>,<NA>,<NA>,2021-S2,2021-S2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
trimestre,categorical,<NA>,<NA>,<NA>,2021-T3,2021-T3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
semestre_precedent,categorical,<NA>,<NA>,<NA>,2021-S1,2021-S1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
annee_precedente,numeric,2021.518344,2021.516581,0.001762,2021.0,2021.0,0.0,1.269153,1.267658,0.001495,2020,2020,2024,2024,0.000087,0.0,0.11795
trimestre_precedent,categorical,<NA>,<NA>,<NA>,2021T2,2021T2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
prix_m2,numeric,6003.199668,5999.136593,4.063075,4764.705882,4764.705882,0.0,3653.826395,3644.720456,9.10594,500.24,501.672241,19998.888889,19994.074074,0.067728,0.0,0.249839
commune_prix_median_m2_semestre_prec,numeric,5825.209948,5826.698196,-1.488248,4480.5,4479.166667,1.333333,2981.649365,2988.122388,-6.473023,729.927007,729.927007,19335.512346,15000.0,-0.025542,0.029767,-0.216625
ecart_prix_median_pct,numeric,7.211141,7.143543,0.067599,-1.184386,-1.046473,-0.137912,54.578923,54.29953,0.279393,-96.338462,-96.180371,998.01085,1048.648649,0.946291,13.178778,0.51454
commune_revenu_median_2020,categorical,<NA>,<NA>,<NA>,32120,32120,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
commune_etablissements_agriculture_2021,numeric,2.143629,2.148458,-0.004829,1.0,1.0,0.0,3.99282,4.014794,-0.021974,0,0,26,26,-0.224756,0.0,-0.547321
commune_etablissements_industrie_2021,numeric,86.595399,86.459078,0.13632,43.0,43.0,0.0,96.96228,96.875682,0.086597,0,0,401,401,0.15767,0.0,0.08939
commune_etablissements_construction_2021,numeric,218.237914,217.765203,0.472711,125.0,125.0,0.0,225.458131,225.454076,0.004054,0,0,918,918,0.217074,0.0,0.001798
commune_etablissements_1_salarie_2021,numeric,2115.737049,2115.617592,0.119457,705.0,699.0,6.0,3011.591905,3013.25543,-1.663525,1,1,16207,16207,0.005646,0.858369,-0.055207
commune_etablissements_10_plus_salaries_2021,numeric,474.151856,473.568733,0.583124,189.0,189.0,0.0,614.44863,614.174232,0.274397,0,0,4156,4156,0.123134,0.0,0.044677
commune_densite_population_active_2020,numeric,6611117213.751064,6597795584.869526,13321628.881538,3701689626.604466,3701689626.604466,0.0,7169819491.003828,7166157897.918444,3661593.085384,1902748.414376,1902748.414376,28657073316.26376,28657073316.26376,0.20191,0.0,0.051096
commune_taux_residences_secondaires,numeric,0.039266,0.039325,-0.00006,0.020526,0.020526,0.0,0.044697,0.044916,-0.000219,0.0,0.0,0.546009,0.546009,-0.151759,0.0,-0.487721
commune_taux_logements_vacants,numeric,0.070273,0.070193,0.000081,0.066348,0.066348,0.0,0.024385,0.024212,0.000173,0.0,0.0,0.402844,0.293882,0.114707,0.0,0.71585
commune_taux_proprietaires,numeric,0.501994,0.502744,-0.000751,0.4613,0.462753,-0.001453,0.170551,0.171003,-0.000452,0.055556,0.135658,0.974575,0.974575,-0.149289,-0.313975,-0.26431
commune_ratio_residences_secondaires_population,numeric,0.034613,0.034709,-0.000096,0.014755,0.014755,0.0,0.049043,0.049337,-0.000295,0.0,0.0,0.85402,0.85402,-0.277759,0.0,-0.597153
commune_densite_residences_principales_2020,numeric,4726750055.137668,4719565423.508512,7184631.629156,2353553893.208462,2353553893.208462,0.0,5471430402.503582,5470555383.191236,875019.312346,1463652.626443,1463652.626443,22674686409.836895,22674686409.836895,0.152231,0.0,0.015995
commune_taux_chomage_15_64,numeric,0.112124,0.112039,0.000085,0.103886,0.103886,0.0,0.033464,0.033446,0.000018,0.0,0.0,0.241688,0.241688,0.075822,0.0,0.052773
commune_taux_emploi,numeric,0.731287,0.731191,0.000096,0.563501,0.563327,0.000173,0.867436,0.87584,-0.008405,0.039533,0.039533,36.551949,36.551949,0.013139,0.030793,-0.959606
commune_evolution_emploi_2014_2020,numeric,0.013954,0.014075,-0.000121,0.007006,0.007006,0.0,0.109724,0.110798,-0.001074,-0.802866,-0.753112,3.32118,3.32118,-0.861455,0.0,-0.969191
commune_part_services_entreprises,numeric,0.173941,0.173802,0.000139,0.165858,0.165858,0.0,0.057191,0.057318,-0.000128,0.0,0.0,1.0,1.0,0.080126,0.0,-0.222992
commune_part_commerce_tourisme,numeric,0.712099,0.711649,0.000451,0.718833,0.716944,0.001889,0.116567,0.117397,-0.00083,0.0,0.0,1.0,1.0,0.063332,0.263531,-0.706783
commune_part_admin_sante,numeric,0.106322,0.106507,-0.000186,0.099314,0.099314,0.0,0.043391,0.043591,-0.0002,0.0,0.0,1.0,1.0,-0.174362,0.0,-0.458846
commune_etablissements_par_menage,numeric,0.092647,0.092587,0.000061,0.072641,0.072351,0.00029,0.09843,0.098361,0.000069,0.011123,0.011123,1.299053,1.299053,0.065421,0.400947,0.070209
commune_taux_etablissements_10_plus,numeric,0.174461,0.174233,0.000228,0.167832,0.167832,0.0,0.057768,0.057785,-0.000017,0.0,0.0,0.555556,0.555556,0.130834,0.0,-0.03002
commune_sante_score_2013_commune,numeric,0.646946,0.64735,-0.000404,0.650911,0.651843,-0.000931,0.088436,0.088471,-0.000035,0.0,0.0,1.0,1.0,-0.062424,-0.142893,-0.039869
commune_education_score_2013_commune,numeric,0.609935,0.609975,-0.00004,0.588408,0.588408,0.0,0.200631,0.20094,-0.000309,0.113469,0.113469,1.0,1.0,-0.00656,0.0,-0.153795
commune_revenu_score_2013_commune,numeric,0.548146,0.548788,-0.000641,0.56364,0.563784,-0.000144,0.16845,0.168521,-0.000071,0.0,0.0,0.947426,0.947426,-0.116857,-0.025527,-0.042389
commune_idh2_2013_commune,numeric,0.601684,0.602038,-0.000355,0.592777,0.592401,0.000377,0.139367,0.139515,-0.000148,0.236949,0.236949,0.904551,0.904551,-0.058884,0.063562,-0.106197
commune_taux_criminalite_moyen,numeric,0.575956,0.575366,0.00059,0.457098,0.457098,0.0,0.517506,0.523956,-0.00645,0.0,0.0,12.795808,12.795808,0.102486,0.0,-1.231014
commune_taux_croissance_pop,numeric,0.433812,0.430031,0.00378,0.270653,0.270653,0.0,1.194161,1.188427,0.005735,-9.889072,-5.811302,15.865758,15.865758,0.879047,0.0,0.482532
commune_densite_pop,numeric,9693.97204,9671.339172,22.632869,5725.265957,5731.900452,-6.634495,10197.525345,10189.966689,7.558656,3.012685,3.171247,39957.220708,39957.220708,0.23402,-0.115747,0.074177

In [10]:
warnings = identifier_differences_significatives(comparison, threshold_mean=0.1, threshold_std=0.2)

# Afficher les alertes
if warnings['mean']:
    print("⚠️ Variables avec différences de moyenne > 10%:")
    for w in warnings['mean']:
        print(f"  - {w['variable']}: {w['diff_pct']:.1f}%")

if warnings['std']:
    print("\n⚠️ Variables avec différences d'écart-type > 20%:")
    for w in warnings['std']:
        print(f"  - {w['variable']}: {w['diff_pct']:.1f}%")

if warnings['distribution']:
    print("\n⚠️ Variables avec plage de valeurs différentes:")
    for w in warnings['distribution']:
        print(f"  - {w['variable']}: train={w['train_range']}, test={w['test_range']}")

⚠️ Variables avec différences d'écart-type > 20%:
  - surface_terrain: -22.7%

⚠️ Variables avec plage de valeurs différentes:
  - latitude: train=[48.125164, 49.234761], test=[48.125164, 49.236552]
  - ecart_prix_median_pct: train=[-96.33846153846154, 998.0108499095842], test=[-96.18037135278514, 1048.6486486486488]

In [11]:
fig = go.Figure()

# Ajouter les distributions
fig.add_trace(go.Box(
    y=train['prix_m2'],
    name='Train',
    boxmean='sd',
    marker_color='lightblue'
))

fig.add_trace(go.Box(
    y=test['prix_m2'],
    name='Test',
    boxmean='sd',
    marker_color='lightgreen'
))

fig.add_trace(go.Box(
    y=out_of_sample_df['prix_m2'],
    name='Out of Sample (2025)',
    boxmean='sd',
    marker_color='lightcoral'
))

# Mise en forme
fig.update_layout(
    title='Comparaison de la distribution de prix_m2 entre les échantillons',
    yaxis_title='Prix au m² (€)',
    showlegend=True,
    height=600,
    template='plotly_white'
)

fig.show()

In [12]:
train.to_parquet("data/processed/train_test_out_sample_split/idf_vf_train.parquet", index=False)
test.to_parquet("data/processed/train_test_out_sample_split/idf_vf_test.parquet", index=False)
out_of_sample_df.to_parquet("data/processed/train_test_out_sample_split/idf_vf_out_of_sample.parquet", index=False)